[package]
name = "pursue"
version = "0.0.1"
authors = ["Sebastian Pineda"]
edition = "2024"

[dependencies]
argparse = "0.2.2"
num_cpus = "1.16.0"

[profile.release-optimized]
inherits = "release"
lto = true
codegen-units = 1
strip = true
